name: Build_1.8.0

on: push

jobs:
  build-windows-msi:
    name: Windows Build (MSI)
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          arch: win32_msvc2019
          cache: true
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Download Tools
        run: python scripts\download.py
      - name: Download OpenSSL
        run: choco install -y openssl.light --version=1.1.1.20181020 --x86 --params "/InstallDir:C:\OpenSSL"
      - name: Build MSI Package
        id: build
        shell: cmd
        run: |
          set QTDIR=%Qt5_DIR%
          set OPENSSL=C:\OpenSSL
          set PATH=%PATH%;C:\Program Files (x86)\WiX Toolset v3.11\bin
          call scripts\windows\packages\msi\build.msi.bat || exit
          set /p VERSION=<VERSION
          echo VERSION=%VERSION%>>%GITHUB_ENV%
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-msi
          path: apk-editor-studio_windows_${{ env.VERSION }}.msi
